---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counterclient
  labels:
    app: counterclient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counterclient
  template:
    metadata:
      labels:
        app: counterclient
    spec:
      containers:
      - name: counterclient-container
        image: druggeri/counterclient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: counterclient
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault